License checker
KnightHacks/Lancelot pull request #42
Opened 2021-12-15 03:15 UTC by rob-3

2021-12-15 03:42 UTC, suneettipirneni requested changes

2021-12-15 03:42 UTC, suneettipirneni commented on src/licenseChecker.ts
> +          })
Usually you don't have to use `.map` in succession, it most likely can be merged into one `.map`:

```suggestion
         .map((r) => {
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            const content = r.value.content!;
            const buffer = Buffer.from(content, 'base64').toString('utf-8');
            return ['copyright', 'license']
              .map((term) => buffer.toLowerCase().includes(term))
              .reduce((acc, cur) => acc || cur);
          })
```

2021-12-15 04:41 UTC, suneettipirneni requested changes

2021-12-15 04:41 UTC, suneettipirneni commented on src/licenseChecker.ts
> +            const buffer = Buffer.from(r.value.content!, 'base64').toString(
Currently you're filter doesn't narrow the type (it still assumes content is nullish even though we know by the time we get to `.map` it *has* to be present). Instead you can use a type predicate on the filter function return type to tell TS that, in fact, those properties are present, and remove the risky non-null assertion `!`.

```suggestion
        const isCopyrightAsserted = responses
          .filter((r): r is { value: { content: string } } => 'value' in r && 'content' in r.value)
          .map((r) => {
            const buffer = Buffer.from(r.value.content, 'base64').toString(
```

2021-12-15 05:17 UTC, suneettipirneni commented on src/licenseChecker.ts
> +          ])
May I ask why `Promise.allSettled` was chose as a opposed to `Promise.all`? `Promise.allSettled` won't reject even if there's an error, while `.all` will

2021-12-15 05:28 UTC, rob-3 commented on src/licenseChecker.ts
> +          ])
My intention was to simply ignore any fetch that failed and proceed with a best effort

2021-12-15 05:29 UTC, rob-3 commented on src/licenseChecker.ts
> +          ])
Although now I'm wondering what would happen if the fetch failed because I forgot to handle that case

2021-12-15 16:37 UTC, suneettipirneni commented on src/licenseChecker.ts
> +          ])
I would just use do a manually fetch for the fist case, if that first case fails then fallback and use the second case. If the second case fails, then allow it to throw.

2021-12-15 17:34 UTC, rob-3 commented on src/licenseChecker.ts
> +          ])
I don't want it to throw though; if requests fail I should probably just log it and send the message anyway. I could change it to be sequential though

2021-12-16 00:48 UTC, suneettipirneni requested changes

2021-12-16 00:48 UTC, suneettipirneni commented on src/licenseChecker.ts
> +        );
```suggestion
      const responses = <PromiseSettledResult<GitHubResponse>[]>(
          await Promise.allSettled(
            ['README', 'README.md'].map((e) =>
              fetch(repo.contents_url.replace(contentsRegex, e)).then((b) =>
                b.json()
              )
            )
          )
        );
```

2021-12-16 00:49 UTC, suneettipirneni requested changes

2021-12-16 00:49 UTC, suneettipirneni commented on src/licenseChecker.ts
> +  if (message.content) {
I'm pretty sure a message always has content.

2021-12-16 20:34 UTC, rob-3 commented on src/licenseChecker.ts
> +  if (message.content) {
I thought that but the docs say it is optional. https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=content

2021-12-16 20:51 UTC, suneettipirneni commented on src/licenseChecker.ts
> +  if (message.content) {
Pretty sure that's wrong, because the discord docs say it isn't optional https://discord.com/developers/docs/resources/channel#message-object

2021-12-16 22:55 UTC, suneettipirneni approved these changes
lgtm

2021-12-16 22:55 UTC, merged